finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib import admin
urlpatterns = [
    path('dashboard/',views.index, name="index"),
    path('about/',views.about,name="about"),
    path('about/hindi',views.hindi,name="hindi"),
    path('coming-soon/',views.comingsoon, name="comingsoon"),
    path('reviews-page/',views.reviewspage, name="reviewspage"),
    path('add-events/',views.addevents, name="addevents"),
    path('add-past-events/',views.addpastevents, name="addpastevents"),
    path('events/',views.events, name="events"),
    path('past-events/',views.past_events, name="past_events"),
    path('feedback/',views.feedback, name="feedback"),
    path('updatefeedback/<int:pk>/',views.updatefeedback, name="updatefeedback"),
    path('contact-page/',views.contactuspage, name="contactuspage"),
    path('login/', views.handleLogin, name='login'),
    path('', views.homepage, name='homepage'),
    path('contact/', views.contactpage, name='contactpage'),
    path('logout/', views.handleLogout, name='handleLogout'),
    path('signup/', views.signUp, name='signUp'),
    path('profile/', views.profile, name='profile'),
    path('payment/', views.payment, name='payment'),
    path('response/', views.response, name='response'), 
    path('admin-home/', views.admin_home, name='admin_home'),
    path('admin-all-transactions/', views.admin_all_transactions, name='admin_all_transactions'),
    path('all-transactions/', views.all_transactions, name='all_transactions'),
    path('admin-all-users/', views.admin_all_users, name='admin_all_users'),
    path('regular-update/', views.regular_update, name='regular_update'), 
    path('fixed-rate-update/', views.fixed_rate_update, name='fixed_rate_update'), 
    path('fixed-rate-page/', views.fixed_rate_page, name='fixed_rate_page'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('company-capital/', views.company_capital_page, name='company_capital'),
    path('admin-withdrawal-requests/', views.admin_withdrawal_requests, name='admin_withdrawal_requests'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset/done', views.password_reset_done, name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
     path('pdf-all-transactions/', views.pdf_all_transactions, name='pdf_all_transactions'),
     path('update-withdraw-status/checkby/nobackallowed/be72fa80-f77c-11ec-b939-0242ac120002/<int:id>/',views.update_withdrawl_requests,name="update_withdrawl_requests"),
     path('delete-withdraw-status/checkby/nobackallowed/be72fa80-f77c-11ec-b939-0242ac120002/<int:id>/',views.delete_withdrawl_requests,name="delete_withdrawl_requests"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin settings
admin.site.site_header = 'GD Capital'                    # default: "Django Administration"
admin.site.index_title = 'Major Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'GD Capital' # default: "Django site admin"

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.conf import settings

PLAN_TYPE = (
    ('fixed','FIXED'),
    ('flexible', 'FLEXIBLE'),
)
DISPLAY_TYPE = (
    ('yes','YES'),
    ('no', 'NO'),
)
User = get_user_model()
class UserProfile(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    plantype = models.CharField(max_length=200, choices=PLAN_TYPE, default='flexible')
    user_commission = models.CharField(max_length=3, null=False, default='25')
    fixed_rate = models.CharField(max_length=3, null=True, default='0')
    profession = models.CharField(max_length=200, null=False, default='')
    mobile = models.CharField(max_length=10, null=False, default='')
    profilephoto = models.ImageField(upload_to='userprofile/', default='images/profile.png')
    pancard = models.ImageField(upload_to='pancard/', default='images/profile.png')
    # total_wallet_money = models.CharField(max_length=10, null=False, default='')
    def __str__(self):
        return self.user.username

class RegularUpdate(models.Model):
    initial_value = models.FloatField()
    final_value = models.FloatField()
    transaction_date_time = models.DateTimeField(auto_now_add=True)
    percent = models.FloatField(null=True, blank=True)
    def save(self, *args, **kwargs):
        self.percent = (self.final_value - self.initial_value)*100/self.initial_value
        super(RegularUpdate, self).save(*args, **kwargs)
    def __str__(self):
        return str(self.transaction_date_time)

class Transaction(models.Model):
    # made_by = models.ForeignKey(User, related_name='transactions', 
    #                             on_delete=models.CASCADE )
    made_by = models.CharField(max_length=100, null=True, blank=True)
    plantype = models.CharField(max_length=200, choices=PLAN_TYPE, default='flexible')
    fixed_rate = models.CharField(max_length=3, null=True, default='3')
    made_on = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()
    present_amount = models.FloatField(null=True, blank=True)
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True)
    checksum = models.CharField(max_length=200, null=True, blank=True)
    txn_id = models.CharField(max_length=100, null=True, blank=True)
    payment_mode = models.CharField(max_length=100, null=True, blank=True,default='')
    status = models.CharField(max_length=100, null=True, blank=True)
    gateway_name = models.CharField(max_length=100, null=True, blank=True)
    bank_txn_id = models.CharField(max_length=100, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    response_message = models.CharField(max_length=250, null=True, blank=True)
    last_updated = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return str(self.order_id)
class Withdraw(models.Model):
    requested_by = models.CharField(max_length=100, null=True, blank=True)
    requested_on = models.DateTimeField(default=timezone.now)
    amount = models.FloatField()
    present_balance = models.FloatField(null=True, blank=True)
    invested_balance = models.FloatField(null=True, blank=True)
    status = models.CharField(max_length=5, null=True, blank=True)
    status_updated_by = models.CharField(max_length=100, null=True, blank=True)
    user_commission = models.FloatField(null=True, blank=True, default=25)
    status_updated_on = models.DateTimeField(null=True, blank=True)
    plantype = models.CharField(max_length=200, choices=PLAN_TYPE, default='',null=True, blank=True)
    def __str__(self):
        return str(self.requested_by)
class CompanyCapital(models.Model):
    commission_by = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    commission = models.FloatField(null=True, blank=True)

    def __str__(self):
        return str(self.commission_by)
class ContactUs(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    message = models.TextField(max_length=100, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.name)

class Event(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    date = models.DateTimeField()

    def __str__(self):
        return str(self.title)
class Review(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    review = models.TextField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    display = models.CharField(max_length=200, choices=DISPLAY_TYPE, default='no',blank=True,null=True)

    def __str__(self):
        return str(self.name)

class PastEvent(models.Model):
    event_name = models.CharField(max_length=100, null=True, blank=True)
    event_date = models.DateTimeField()
    star_client_image = models.ImageField(upload_to='pastevents/', default='images/profile.png')
    star_client_name = models.CharField(max_length=100, null=True, blank=True)
    client1_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client2_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client3_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client4_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client5_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client6_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client7_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client8_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client9_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client10_image = models.ImageField(upload_to='pastevents/', null=True, blank=True)
    client1_name = models.CharField(max_length=100, null=True, blank=True)
    client2_name = models.CharField(max_length=100, null=True, blank=True)
    client3_name = models.CharField(max_length=100, null=True, blank=True)
    client4_name = models.CharField(max_length=100, null=True, blank=True)
    client5_name = models.CharField(max_length=100, null=True, blank=True)
    client6_name = models.CharField(max_length=100, null=True, blank=True)
    client7_name = models.CharField(max_length=100, null=True, blank=True)
    client8_name = models.CharField(max_length=100, null=True, blank=True)
    client9_name = models.CharField(max_length=100, null=True, blank=True)
    client10_name = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return str(self.event_name)

templates/admin-templates/add-past-events.html
{% extends 'admin-templates/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

<h3 class="display-4" style="color:#ece6dc; font-size:30px !important">Add Past Events 
</h3>
{% if messages %}
                {% for message in messages %}
                <div class="alert alert-success my-3" style="border:0 !important">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}
<div class="card shadow my-4" style="border: 0 !important;border-radius:15px">

    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-0">
                    {{ form.event_name|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.event_date|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.star_client_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.star_client_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client1_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client1_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client2_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client2_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client3_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client3_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client4_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client4_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client5_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client5_name|as_crispy_field }}
                </div>


                <div class="col-md-6 mb-0">
                    {{ form.client6_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client6_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client7_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client7_name|as_crispy_field }}
                </div>
                
                <div class="col-md-6 mb-0">
                    {{ form.client8_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client8_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client9_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client9_name|as_crispy_field }}
                </div>

                <div class="col-md-6 mb-0">
                    {{ form.client10_image|as_crispy_field }}
                </div>
                <div class="col-md-6 mb-0">
                    {{ form.client10_name|as_crispy_field }}
                </div>
                
                
                
            </div>
            
            <div class="form-group text-end">
                <input type="submit" value="Add" class="btn btn-dark px-3" style="background-color:#464343;font-size:0.8rem;">
            </div>
            
        </form>


    </div>
</div>
<script>
    $(document).ready( function () {
    $('#transTable').DataTable({
        order: [[1, 'asc']],
    });
} );
</script>
{% endblock content %}

templates/admin-templates/admin-all-transaction.html
{% extends 'admin-templates/base.html' %}
{% load static %}
{% block content %}

<h3 class="display-4" style="color:#ece6dc; font-size:30px !important">All Transactions 
    <a href="/pdf-all-transactions" target="_blank"><i style="font-size: 1.3rem;color:red;" class="fa fa-download"></i></a>
</h3>
<div class="card shadow my-4" style="border: 0 !important;border-radius:15px">

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-sm" id="transTable">
                <thead>
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Order Id</th>
                        <th scope="col">Transaction Id</th>
                        <th scope="col">Payment Mode</th>
                        <th scope="col">Status</th>
                        <th scope="col">Gateway Name</th>
                        <th scope="col">Bank Transaction Id</th>
                        <th scope="col">Bank Name</th>
                        <th scope="col">Comments</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in transaction %}
                    <tr>
                        <td>{{transaction.made_by}}</td>
                        <td>{{transaction.made_on|date:'d-m-Y'}}</td>
                        <td>{{transaction.amount|floatformat:2}}</td>
                        <td>{{transaction.order_id}}</td>
                        <td>
                            {% if transaction.status == 'TXN_SUCCESS' %}
                            <span style="color:green">
                                {{transaction.txn_id}}
                            </span>
                            {% else %}
                            <span style="color:red">
                                {{transaction.txn_id}}
                            </span>
                            {% endif %}
                            </td>
                        <td>{{transaction.payment_mode}}</td>
                        <td>{{transaction.status}}</td>
                        <td>{{transaction.gateway_name}}</td>
                        <td>{{transaction.bank_txn_id}}</td>
                        <td>{{transaction.bank_name}}</td>
                        <td>{{transaction.response_message}}</td>
                    </tr>
                    {% endfor %}
                    
                    
                </tbody>
            </table>
        </div>


    </div>
</div>
<script>
    $(document).ready( function () {
    $('#transTable').DataTable({
        order: [[1, 'asc']],
    });
} );
</script>
{% endblock content %}

templates/admin-templates/admin-home.html
{% extends 'admin-templates/base.html' %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-4 col-4 col-md-4">
      <div class="card dashboard-card px-3 mt-4">
          <div class="card-body">
              <p class="inv-txt">Invested Amount</p>
              <div class="text-center" style="display:flex; justify-content:center">
                  <i class="bi bi-currency-rupee"></i>
                  <h2 id="invested-amount" class="inv-amt m-0" style="display:inline">{{total_money|floatformat:2}}</h2>
              </div>
              
          </div>
      </div>
  </div>
  <div class="col-lg-4 col-4 col-md-4">
      <div class="card dashboard-card px-3 mt-4" style="transform:scale(1.01)">
          <div class="card-body">
              <p class="inv-txt">Current Amount </p>
              <div class="text-center" style="display:flex; justify-content:center">
                  <i class="bi bi-currency-rupee"></i>
                  <h2 class="inv-amt m-0" id="present-amount" style="display:inline">
                    {% if total_present_value >= total_money %}
                    <span style="color:green">{{total_present_value|floatformat:2}}</span>
                    {% else %}
                    <span style="color:red">{{total_present_value|floatformat:2}}</span>
                    {% endif %}
                    
                  </h2>
                  
              </div>
              
          </div>
      </div>
  </div>
  <div class="col-lg-4 col-4 col-md-4">
    <div class="card dashboard-card px-3 mt-4">
        <div class="card-body">
            <p class="inv-txt">
              {% if perc >= 0 %}
              Profit
                    {% else %}
                    Loss
                    {% endif %} Percent
            </p>
            <div class="text-center" style="display:flex; justify-content:center">
                <i class="bi bi-percent"></i>
                <h2 id="invested-amount" class="inv-amt m-0" style="display:inline">
                  {% if perc >= 0 %}
                    <span style="color:green">{{perc|floatformat:2}}</span>
                    {% else %}
                    <span style="color:red">{{perc|floatformat:2}}</span>
                    {% endif %}
                  
                </h2>
            </div>
            
        </div>
    </div>
</div>
  
</div>

        {% comment %} <div id="container"style="display:flex;justify-content:center;align-items: center;" class="my-3">
            <canvas id="pie-chart" style="height:20rem; width:20rem"></canvas>
          </div> {% endcomment %}
        <div class="card shadow-sm mt-4" style="border: 0 !important;border-radius:15px">

            <div class="card-body  ">
                <div class="table-responsive">
                    <table class="table table-sm" id="transTable">
                        <thead>
                            <tr>
                                <th scope="col">Username</th>
                                <th scope="col">Invested Amount</th>
                                <th scope="col">Present Amount</th>
                                <th scope="col">Amount Deposited On</th>
                                <th scope="col">Plan Type</th>
                                <th scope="col">Last Updated</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in result %}
                            {% if i.status == 'TXN_SUCCESS' %}
                            <tr>
                                <td>{{i.made_by}}</td>
                                <td>{{i.amount|floatformat:2}}</td>
                                <td>{{i.present_amount|floatformat:2}}</td>
                                <td>{{i.made_on}}</td>
                                <td>{{i.plantype}}</td>
                                <td>{{i.last_updated}}</td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                            
                            
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
        <script>
            $(document).ready( function () {
            $('#transTable').DataTable();
        } );
        </script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        
{% endblock content %}

templates/admin-templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Admin Panel- GD Capital</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>

<body>
    {% if request.user.is_superuser %}
    <!-- Vertical navbar -->
    <div class="vertical-nav dark-bg" id="sidebar">
        <div class="py-2 px-3 dark-bg">
            <div class="media d-flex align-items-center">
                <img loading="lazy" src="{% static 'images/logo.png' %}" alt="..."
                    width="80" height="80" class="mr-3 rounded-circle img-thumbnail shadow">
                <div class="media-body">
                    <h4 class="m-0" style="font-weight:700;color:#ece6dc;">GD Capital</h4>
                    <p class="font-weight-normal text-muted mb-0 welcome-text">Welcome <span style="color:red;">{{request.user.username|title}}</span></p>
                </div>
            </div>
        </div>
        <div class="container">
            <a href="/" class="text-dark back-arrow"><i class="bi bi-arrow-left-circle text-white" style="font-size: 1.2rem;"></i></a>
          </div>
        <p class="text-gray font-weight-bold text-uppercase px-3 small pb-1 mb-0 mt-2">MENU</p>
        
        <ul class="nav flex-column mb-0">
            
            <li class="nav-item">
                <a href="/admin-home" class="nav-link text-dark ">
                    <i class="fa fa-th-large mr-3 text-primary fa-fw"></i>
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a href="/admin-all-transactions" class="nav-link text-dark">
                    <i class="fa fa-upload mr-3 text-primary fa-fw"></i>
                    All Transactions
                </a>
            </li>
            <li class="nav-item">
                <a href="/signup" class="nav-link text-dark">
                    <i class="fa fa-plus mr-3 text-primary fa-fw"></i>
                    Add New User
                </a>
            </li>
            <li class="nav-item">
                <a href="/admin-all-users" class="nav-link text-dark">
                    <i class="fa fa-users mr-3 text-primary fa-fw"></i>
                    All User Profiles
                </a>
            </li>
            <li class="nav-item">
                <a href="/regular-update" class="nav-link text-dark">
                    <i class="fa fa-calendar mr-3 text-primary fa-fw"></i>
                    Flexible Regular Update
                </a>
            </li>
            <li class="nav-item">
                <a href="/fixed-rate-page" class="nav-link text-dark">
                    <i class="fa fa-certificate mr-3 text-primary fa-fw"></i>
                    Fixed Regular Update
                </a>
            </li>
            <li class="nav-item">
                <a href="/admin-withdrawal-requests" class="nav-link text-dark">
                    <i class="fa fa-angle-right mr-3 text-primary fa-fw"></i>
                    Withdrawal Requests
                </a>
            </li>
            <li class="nav-item">
                <a href="/admin" class="nav-link text-dark">
                    <i class="fa fa-lock mr-3 text-primary fa-fw"></i>
                    Major Admin Panel
                </a>
            </li>
            <li class="nav-item">
                <a href="/company-capital" class="nav-link text-dark">
                    <i class="fa fa-barcode mr-3 text-primary fa-fw"></i>
                    Company Capital
                </a>
            </li>
            <li class="nav-item">
                <a href="/add-events" class="nav-link text-dark">
                    <i class="fa fa-star mr-3 text-primary fa-fw"></i>
                    Add Upcoming Events
                </a>
            </li>
            <li class="nav-item">
                <a href="/add-past-events" class="nav-link text-dark">
                    <i class="fa fa-star mr-3 text-primary fa-fw"></i>
                    Add Past Events
                </a>
            </li>
            <li class="nav-item">
                <a href="/contact-page" class="nav-link text-dark">
                    <i class="fa fa-check mr-3 text-primary fa-fw"></i>
                    Contact
                </a>
            </li>
            <li class="nav-item">
                <a href="/reviews-page" class="nav-link text-dark">
                    <i class="fa fa-envelope mr-3 text-primary fa-fw"></i>
                    Reviews
                </a>
            </li>
            <li class="nav-item">
                <a href="/logout" class="nav-link text-dark">
                    <i class="fa fa-exclamation mr-3 text-primary fa-fw"></i>
                    Logout
                </a>
            </li>
        </ul>


    </div>
    <!-- End vertical navbar -->


    <!-- Page content holder -->
    <div class="page-content p-5" id="content">
        <!-- Toggle button -->
        <!-- <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
                class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button> -->
        <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow px-4 mb-4"><i
                class="fa fa-bars "></i></button>

        <!-- Demo content -->
        {% block content %}{% endblock content %}
        
    </div>
    <!-- End demo content -->
    {% else %}
    You are not a authorised user to access this page. Go back to <a href="/">home</a>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    <script>
        $(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
            });
        });
        $( document ).ready(function() {
            $('#id_plantype').on('change', function (e) {
                var optionSelected = $("option:selected", this);
                var valueSelected = this.value;
            
                if (valueSelected === 'fixed'){
                    $('#fixed-rate-div').show();
                } else {
                    $('#fixed-rate-div').hide();
                }
            });
        });
    </script>
</body>

</html>

templates/admin-templates/fixed-rate-update.html
{% extends 'admin-templates/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow my-4" style="border: 0 !important;border-radius:15px">

            <div class="card-body text-center ">
                
                <h3 class="display-4" style="color:#272727; font-size:30px !important">Fixed Update</h3>
                    <div style="display:flex;justify-content:center;align-items:center">
                        <p style="color:red;">
                            Click on the button once in a day.
                        </p>
                        
                    </div>
                    <a href="/fixed-rate-update" class="btn btn-dark btn-block">Regular Fixed Rate</a>
                    
                    
                
            </div>
        </div>
        
        <script>
            $(document).ready( function () {
            $('#transTable').DataTable();
        } );
        </script>
{% endblock content %}

templates/admin-templates/user-wallets.html
user wallets